pipelines:
  - name: cache_test
    steps:
      - name: frontend_build
        type: Bash
        configuration:
          inputResources:
            - name: frontend_gitRepo
          integrations:
            - name: int_default_artifactory
        execution:
          onStart:
            - pushd $res_frontend_gitRepo_resourcePath
            - pushd frontend
            - mkdir -p /tmp/npm_cache
            - restore_pipeline_files npm_cache /tmp/npm_cache/
            - jfrog rt npmc --server-id-resolve int_default_artifactory --repo-resolve npm-remote
            - jfrog rt npmci --cache /tmp/npm_cache --prefer-offline
            - add_pipeline_files /tmp/npm_cache npm_cache
            - echo "completed"